# Generated by Django 6.0.3 on 2026-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9, verbose_name='CEP da Loja'),
        ),
    ]
