# Generated by Django 6.0.3 on 2026-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_custo_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliações'},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='custo',
            new_name='preco_custo',
        ),
    ]
