# Generated by Django 6.0.3 on 2026-05-12 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_custo_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliações'},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='custo',
            new_name='preco_custo',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ (1) Ruim'), (2, '⭐⭐ (2) Regular'), (3, '⭐⭐⭐ (3) Bom'), (4, '⭐⭐⭐⭐ (4) Muito Bom'), (5, '⭐⭐⭐⭐⭐ (5) Excelente')]),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('usuario', 'produto')},
        ),
    ]
