# Generated by Django 6.0.3 on 2026-05-16 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_loja_cep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
