# Generated by Django 6.0.3 on 2026-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfil_foto_perfil_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('smartphones', 'Smartphones'), ('notebooks', 'Notebooks'), ('acessorios', 'Acessórios')], max_length=50, null=True),
        ),
    ]
