# Generated by Django 6.0.3 on 2026-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_produto_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('smartphones', 'Smartphones'), ('notebooks', 'Notebooks'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], max_length=50, null=True),
        ),
    ]
