# Generated by Django 6.0.3 on 2026-05-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco_unitario',
            new_name='preco',
        ),
    ]
